# Uncomment the next line to define a global platform for your project
# platform :ios, '14.1'

target 'Flavorful' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flavorful


  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  use_frameworks!
  pod 'ReachabilitySwift'
  pod 'Alamofire'
 
  target 'FlavorfulTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlavorfulUITests' do
    # Pods for testing
  end

end
